openapi: 3.0.3
info:
  title: Shared Error Definitions
  version: 1.0.0

components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
        traceId:
          type: string
